runtime: go125  # or go120, depending on your Go version previously used go122
instance_class: F1  # Adjust this based on your app needs


automatic_scaling:
  max_instances: 5


handlers:
  - url: /static
    static_dir: static

  - url: /image
    static_dir: image

  # Catch-all handler for dynamic content (Gin app)
  - url: /.*
    script: auto

env_variables:
  GIN_MODE: release  # Set Gin to release mode for production
